# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d4f1302273e33a1a7bfa9af813440139c5497d02c84825b74083e6b066f02f112c0ec81f69b10fe0f4a12bc8896f0dedfd3d427dec6ebcf839ea092291e2820

test:
  secret_key_base: 9d34e170b592312f3fa7d5fc002fe1da9a1fa90281623cb36b924630bbbe141af50ef83f5c068d264e596282899770780c12ae1ec6241442495b955b86785262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
